version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"  # Next.js
      - "8000:8000"  # FastAPI
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
